spring:
  application:
    name: security-codebase
  security:
    user:
      name: akshay
      password: akshay
      roles: ADMIN #spring security will automatically add ROLE_ prefix to the role name, so it will be ROLE_ADMIN
